project_id = "xdbhyywhniywotdntxud"

[functions.test]
verify_jwt = false

[functions.chat]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.manage-subscription]
verify_jwt = true

[functions.file-upload]
verify_jwt = true

[functions.save-chat]
verify_jwt = true

[functions.get-chat-history]
verify_jwt = true

[functions.check-conversation-limit]
verify_jwt = true

[functions.admin-dashboard]
verify_jwt = true

[functions.chat-with-gemini]
verify_jwt = true

[functions.rag-chatbot]
verify_jwt = false
